package com.example.moviesapp.ui.constants

internal const val PACKAGE_NAME = "com.example.moviesapp"
//Login Graph Routes
internal const val ROUTE_LOGIN_GRAPH = "$PACKAGE_NAME.ROUTE_LOGIN_GRAPH"
internal const val ROUTE_WELCOME_SCREEN = "$PACKAGE_NAME.ROUTE_WELCOME_SCREEN"
internal const val ROUTE_LOGIN_SCREEN = "$PACKAGE_NAME.ROUTE_LOGIN_SCREEN"
internal const val ROUTE_SIGN_UP_SCREEN = "$PACKAGE_NAME.ROUTE_SIGN_UP_SCREEN"
internal const val ROUTE_FORGOT_PASSWORD_SCREEN = "$PACKAGE_NAME.ROUTE_FORGOT_PASSWORD_SCREEN"
internal const val ROUTE_CHECK_EMAIL_SCREEN = "$PACKAGE_NAME.ROUTE_CHECK_PASSWORD_SCREEN"
internal const val ROUTE_RESET_PASSWORD_SCREEN = "$PACKAGE_NAME.ROUTE_RESET_PASSWORD_SCREEN"

//Main Graph Routes
internal const val ROUTE_MAIN_SCREEN = "$PACKAGE_NAME.ROUTE_MAIN_SCREEN"