package com.example.moviesapp.ui.constants

const val PACKAGE_NAME = "com.example.moviesapp.ui"
//Login Graph Routes
const val ROUTE_LOGIN_GRAPH = "$PACKAGE_NAME.ROUTE_LOGIN_GRAPH"
const val ROUTE_WELCOME_SCREEN = "$PACKAGE_NAME.ROUTE_WELCOME_SCREEN"
const val ROUTE_LOGIN_SCREEN = "$PACKAGE_NAME.ROUTE_LOGIN_SCREEN"
const val ROUTE_SIGN_UP_SCREEN = "$PACKAGE_NAME.ROUTE_SIGN_UP_SCREEN"
const val ROUTE_FORGOT_PASSWORD_SCREEN = "$PACKAGE_NAME.ROUTE_FORGOT_PASSWORD_SCREEN"
const val ROUTE_CHECK_EMAIL_SCREEN = "$PACKAGE_NAME.ROUTE_CHECK_PASSWORD_SCREEN"
const val ROUTE_RESET_PASSWORD_SCREEN = "$PACKAGE_NAME.ROUTE_RESET_PASSWORD_SCREEN"